# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: make the gradle executable
        run: |
          chmod +x ./gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build

      - name: Check the Java & gradle version
        run: |
          .\gradlew  -version

      - name: Execute the Testcases
        run: |
          java -jar ./output/Cucumber7X-1.0.0-all.jar
          .\gradlew  test


      - name: Html file generate
        if: always ()
        run: |
          startline=$(sed -n '/<table/=' cucumber-reports/generated/html/cucumber-html-reports/overview-features.html | tail -1)
          endline=$(sed -n '/table>/=' cucumber-reports/generated/html/cucumber-html-reports/overview-features.html |tail -1)
          echo $startline, $endline
          sed -n "$startline,$endline p" cucumber-reports/generated/html/cucumber-html-reports/overview-features.html > cucumber-reports/temp_file.html
          sed -i -e '/Build Version:/r cucumber-reports/temp_file.html' cucumber-reports/email.html
          sed -i 's/0000/${{ github.run_id }}/g' cucumber-reports/email.html
          echo "<br>Branch:<b>${{ github.ref_name }}</b>" > cucumber-reports/temp_file.html
          sed -i -e '/Suite: /r cucumberReports/temp_file.html' cucumber-reports/email.html

      - uses: actions/upload-artifact@v4
        with:
          name: TestReport-artifact
          path: cucumber-reports/generated/html/cucumber-html-reports

      - uses: actions/upload-artifact@v4
        with:
          name: CucumberReport-Summary-email
          path: cucumber-reports/email.html

