name: Java mail send

on:
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      # - name: Build with Gradle
      #   uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      #   with:
      #     arguments: build
      - name: Send mail Report
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          Secure: false
          username: ${{secrets.EMAIL_USERNAME}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: HumbleBeast Manual Execution Summary for Docker
          to: p.mrutyunjaya.das@gmail.com
          from: HumbleBeast-Test-Alert <jujuaditya037@gmail.com>
          html_body: file://cucumber-reports/email.html
          ignore_cert: true
          convert_ markdown: true
          priority: 'normal'
